### PR TITLE
Adding ARM support for flycapture 2.x

### PR DESCRIPTION
**Pull request by l0g1x**
This will allow ARM users to use this pointgrey camera driver. File structure in the ARM download is different from x86 download, so some folder/file relocation needed to be done in order to compile successfully.

### CODE REVIEW

**Comment by l0g1x** [comment]
okay got it to work. Will do clean up and place things in /usr folder. Silly question, would you happen to know how i could visualize the image? echo'ing the topic works (with some image consistency issues), but when i do rosrun image_view image_view image:=/camera/image i get a md5 error, which i felt like wasnt a issue when i ran on x86 (may be wrong). im using Jetson TK1 as my ARM board

**Comment by l0g1x** [comment]
also, in the wiki http://wiki.ros.org/pointgrey_camera_driver under troubleshooting, the sysctl link to pointgrey's website is not working

**Comment by mikepurvis** [comment]
Fixed the sysctl KB link.

Re: MD5 sum mismatch, note that `/camera/image` is a WFOVImage; you probably meant to check out the `camera/image_raw` topic, which should be image_view-friendly.

Re: /usr and dpkg expansion, do whatever's most convenient, but I would be just as happy to have the contents of the expanded `usr` dir copied up a level as I would having the contents of the armhf archive pushed down into usr dir.

**Comment by l0g1x** [comment]
Yeah i knew about the different message types, i think what confused me was that nothing was showing up in the image_view window when subscribing to `/camera/image_raw` , but when echo'd image_raw, i was seeing data.

**Comment by mikepurvis** [comment]
Is this good to go in?

**Comment by l0g1x** [comment]
I will wrap this up now

**Comment by l0g1x** [comment]
Okay think its good. Removed all debug, and got rid of branching in cmake like you asked. Let me know if theres anything you see

**Pull request merged**
