### PR TITLE
Removed hardcoded strobe configuration for GPIO

### PR DESCRIPTION
**Pull request by evalkaz94**
Instead of having hardcoded GPIO pin number for strobe added same options as triggers.

### CODE REVIEW

**Comment by mikepurvis** [comment]
This seems reasonable, but I'm concerned that it will break anyone with a pre-existing configuration using the old parameter names. What do you think is the best way to proceed here?

**Comment by evalkaz94** [comment]
I see two ways of doing it:
- leaving names as they are and just adding strobe_source parameter with default value GPIO1. That may lead to some misunderstanding but it will not break pre-existing configuration
- another way is to do it like [http://wiki.ros.org/xacro](xacro). In new ROS release add to wiki "New in ..." and have these changes in new release

What do you think about it?

**Comment by BenBlumer** [comment]
Check out pull request #91 -- I've added a hard option to strobe on GPIO2. It's not as classy as this, but it keeps backwards compatibility. It'd be nice to be able to set whichever GPIOs, but GPIO1 and GPIO2 are the only ones that PointGrey recommends in their [literature](http://www.ptgrey.com/KB/11052) anyways.

**Comment by bdholt1** [comment]
If we use the FlyCapture software as a reference, then I'm inclined to suggest that we go with #91.  It makes sense to me to make the dynamic reconfigure parameters mimic the FlyCapture demo software as closely as possible to 

- make it more intuitive for new users of this software to set parameters to achieve their goal
- make it easier to get official support from Point Grey when something isn't working well

What do you think?

**Comment by mikepurvis** [comment]
Closed in favour of #91. Thanks!

**Pull request closed without merging**
